version: '#{build} on {branch}'
image: Visual Studio 2013
clone_depth: 1
branches:
  only:
  - master
  
environment:
  nodejs_version: 'LTS'

install:
- ps: Install-Product node $env:nodejs_version
- cmd: >-
    node --version
    
    npm --version
    
    npm install

build: off
test_script:
- cmd: npm test