#!/bin/sh
WINDOW_ID=$1

SCREENSHOT_DIR=$2
SCREENSHOT_FILENAME=$3
SCREENSHOT_PATH="$SCREENSHOT_DIR/$SCREENSHOT_FILENAME"

THUMBNAIL_DIR=$4
THUMBNAIL_WIDTH=$5
THUMBNAIL_HEIGHT=$6
THUMBNAIL_PATH="$THUMBNAIL_DIR/$SCREENSHOT_FILENAME"

if [ ! -d "$SCREENSHOT_DIR" ]; then
    mkdir "$SCREENSHOT_DIR"
fi

import -window "$WINDOW_ID" "$SCREENSHOT_PATH"

if [ ! -d "$THUMBNAIL_DIR" ]; then
    mkdir "$THUMBNAIL_DIR"
fi

convert "$SCREENSHOT_PATH" -resize "${THUMBNAIL_WIDTH}x${THUMBNAIL_HEIGHT}" "$THUMBNAIL_PATH"
